name: Jenkins Build Request
description: Submit a Jenkins job with parameters
title: "[Build] "
labels: [build-request]
assignees: []
body:
  - type: dropdown
    id: job_type
    attributes:
      label: Job Type
      description: What type of job do you want to run?
      options:
        - Full Build
        - Validation Only
        - Custom Script
    validations:
      required: true

  - type: textarea
    id: parameters
    attributes:
      label: Build Parameters
      description: Provide any custom parameters in JSON format
      placeholder: |
        {
          "target": "ALICE",
          "priority": "high",
          "alidist-branch": "",
          "alidist-tag": "",
          "release-name": "",
          "relval": "False"
        }
    validations:
      required: false