# A action to produce the O2DPG filegraph artefact.
# This can be used to optimize runtime execution and delete files early
name: O2DPG file-graph generation

on:
  workflow_dispatch:  # manual trigger

permissions:
  contents: write # allow push

jobs:
  graph-artefact:
    runs-on: [self-hosted, alibi-cvmfs]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Important for git history

      - name: Fetch base branch
        run: git fetch origin ${{ github.base_ref }} --depth=1

      - name: Compile monitor
        run: |
          # checkout the code and compile
          git clone https://github.com/AliceO2Group/O2DPG O2DPG
          cd O2DPG/UTILS/FileIOGraph
          g++ monitor_fileaccess.cpp -O2 -o monitor_fileaccess.exe
          
      - name: Launch the daemon and run workflow
        id: tags
        shell: bash
        run: |          
          # find out the PID of this shell
          export MAXMOTHERPID=$$
          ./O2DPG/UTILS/FileIOGraph/monitor_fileaccess.exe &> fileaccess_log &
          MONITOR_PID=$!

          # now start the MC workflow
          ls # just a placeholder

          sleep 1

          # bring down the fileaccess_monitor
          kill -9 ${MONITOR_PID}
          cat fileaccess_log

      - name: Produce the graph
        id: graph
        run: |

      - name: Publish the graph
        run: |
          exit 0
        