name: Nightly-MC status collector

on:
  schedule:
    - cron: "0 * * * *"   # runs every hour (0 minute)
  workflow_dispatch:       # allow manual trigger

permissions:
  contents: write # allow push 

jobs:
  collect:
    runs-on: [self-hosted, cern-sso]
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Checkout repo in main branch
        uses: actions/checkout@v4
        with:
          ref: master
          path: repo-master

      - name: Set up Python venv
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install requests beautifulsoup4

      - name: Run job collectors
        run: |
          source .venv/bin/activate
          mkdir -p data
          collector_script=workflow_scripts/lpmtype_jobinfo_collector.py
          
          mkdir -p o2sim_nightlies_status || " dir exists already " 
          LPMTYPES=(27506 27507 30350)
          for i in "${!LPMTYPES[@]}"; do
            type="${LPMTYPES[$i]}"
            echo "Processing type=$type with label=$label"
            python3 ${collector_script} --lpmtype ${type} --output o2sim_nightlies_status/jobs_${type}.json
          done

      # should get the merged datasets
      - name: Fetch existing branch
        run: |
          git config user.name "actions-bot"
          git config user.email "actions-bot@users.noreply.github.com"

          BRANCH="O2sim-nightly-status"
          git fetch origin $BRANCH || true
          git checkout -B $BRANCH origin/$BRANCH || git checkout -B $BRANCH

      - name: Merge JSONs
        run: |
          source .venv/bin/activate
          LPMTYPES=(27506 27507 30350)

          # loop over indices
          for i in "${!LPMTYPES[@]}"; do
            type="${LPMTYPES[$i]}"
            echo "Processing type=$type"
            python3 workflow_scripts/lpmtype_jobinfo_merger.py o2sim_nightlies_status/jobs_${type}.json \
                    --output o2sim_nightlies_status/merged_${type}.json
          done

      - name: Produce nightly status badge
        run: |
          source .venv/bin/activate
          # define arrays
          LABELS=("PbPb nightly (27506)" "pp nightly (27507)" "Anchor PbPb (30350)")
          LPMTYPES=(27506 27507 30350)

          # loop over indices
          for i in "${!LPMTYPES[@]}"; do
            label="${LABELS[$i]}"
            type="${LPMTYPES[$i]}"
            echo "Processing type=$type with label=$label"
            python3 workflow_scripts/produce_nightlies_badge.py \
              --status-file "o2sim_nightlies_status/merged_${type}.json" \
              --badge-file "o2sim_nightlies_status/badge_${type}.json" \
              --label "$label"
          done

      - name: Communicate to mattermost
        env:
          ALIPERF_MATTERMOST_API_TOKEN : ${{ secrets.aliperf_mattermost_token }}
        run: |
          source .venv/bin/activate
          pip3 install mattermostdriver
          
          python3 repo_master/workflow_scripts/publish_nightlies_mattermost.py --api-token "${ALIPERF_MATTERMOST_API_TOKEN}" --text "Hello from github"

      - name: Commit and push results
        run: |
          # stage and commit changes
          git add o2sim_nightlies_status/merged*.json
          git add o2sim_nightlies_status/badge*.json
          git commit -m "Update nightly job status" || echo "No changes to commit"
          BRANCH="O2sim-nightly-status"
          # git push origin HEAD:${{ github.ref }}
          git push --set-upstream origin $BRANCH
